# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b473c1a6fbf8f3dceeb4c2045433ce4c7253c0a7fddb62b5af7777717c55e72bc9ff4facf2517a56c383922e90e2c5ba70be49dcc1075e01be60d3b8805fa3

test:
  secret_key_base: 99bb78fb3f333f6cc1f4ab9e8ec4e7d4b829ab9d77528a08e73fb17d21abf776bdde5d919ab687f43cfaf6ab82301035ccaf78667b60cd9b0b439e53362460db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
